use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    fa_torrent::run()
}
